package com.swamedia.soki.sms.model;
// Generated Aug 26, 2016 3:18:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * POperator generated by hbm2java
 */
@Entity
@Table(name = "P_OPERATOR", schema = "SOKITEST5")
public class POperator implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idTbl;
	private String idoperator;
	private String namaoperator;
	private String alamat;
	private String telepon;
	private String keterangan;
	private String idgroup;
	private String logo;
	private String telegram;
	private String hp;

	public POperator() {
	}

	public POperator(BigDecimal idTbl, String idoperator, String namaoperator, String alamat, String telepon,
			String keterangan, String idgroup, String logo) {
		this.idTbl = idTbl;
		this.idoperator = idoperator;
		this.namaoperator = namaoperator;
		this.alamat = alamat;
		this.telepon = telepon;
		this.keterangan = keterangan;
		this.idgroup = idgroup;
		this.logo = logo;
	}

	public POperator(BigDecimal idTbl, String idoperator, String namaoperator, String alamat, String telepon,
			String keterangan, String idgroup, String logo, String telegram, String hp) {
		this.idTbl = idTbl;
		this.idoperator = idoperator;
		this.namaoperator = namaoperator;
		this.alamat = alamat;
		this.telepon = telepon;
		this.keterangan = keterangan;
		this.idgroup = idgroup;
		this.logo = logo;
		this.telegram = telegram;
		this.hp = hp;
	}

	@Id

	@Column(name = "ID_TBL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTbl() {
		return this.idTbl;
	}

	public void setIdTbl(BigDecimal idTbl) {
		this.idTbl = idTbl;
	}

	@Column(name = "IDOPERATOR", nullable = false, length = 4)
	public String getIdoperator() {
		return this.idoperator;
	}

	public void setIdoperator(String idoperator) {
		this.idoperator = idoperator;
	}

	@Column(name = "NAMAOPERATOR", nullable = false, length = 50)
	public String getNamaoperator() {
		return this.namaoperator;
	}

	public void setNamaoperator(String namaoperator) {
		this.namaoperator = namaoperator;
	}

	@Column(name = "ALAMAT", nullable = false, length = 100)
	public String getAlamat() {
		return this.alamat;
	}

	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}

	@Column(name = "TELEPON", nullable = false, length = 12)
	public String getTelepon() {
		return this.telepon;
	}

	public void setTelepon(String telepon) {
		this.telepon = telepon;
	}

	@Column(name = "KETERANGAN", nullable = false, length = 100)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@Column(name = "IDGROUP", nullable = false, length = 4)
	public String getIdgroup() {
		return this.idgroup;
	}

	public void setIdgroup(String idgroup) {
		this.idgroup = idgroup;
	}

	@Column(name = "LOGO", nullable = false, length = 50)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "TELEGRAM", length = 20)
	public String getTelegram() {
		return this.telegram;
	}

	public void setTelegram(String telegram) {
		this.telegram = telegram;
	}

	@Column(name = "HP", length = 20)
	public String getHp() {
		return this.hp;
	}

	public void setHp(String hp) {
		this.hp = hp;
	}

}
