package com.swamedia.soki.sms.model;
// Generated Aug 26, 2016 3:18:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * TAlert generated by hbm2java
 */
@Entity
@Table(name = "T_ALERT", schema = "SOKITEST5")
public class TAlert implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idAlert;
	private String pesan;
	private String titikAlert;
	private String tujuan;
	private String operatorTujuan;
	private String media;
	private BigDecimal status;
	private String tanggalKirim;
	private String tanggal;

	public TAlert() {
	}

	public TAlert(BigDecimal idAlert) {
		this.idAlert = idAlert;
	}

	public TAlert(BigDecimal idAlert, String pesan, String titikAlert, String tujuan, String operatorTujuan,
			String media, BigDecimal status, String tanggalKirim, String tanggal) {
		this.idAlert = idAlert;
		this.pesan = pesan;
		this.titikAlert = titikAlert;
		this.tujuan = tujuan;
		this.operatorTujuan = operatorTujuan;
		this.media = media;
		this.status = status;
		this.tanggalKirim = tanggalKirim;
		this.tanggal = tanggal;
	}

	@Id
	@Column(name = "ID_ALERT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdAlert() {
		return this.idAlert;
	}

	public void setIdAlert(BigDecimal idAlert) {
		this.idAlert = idAlert;
	}

	@Column(name = "PESAN")
	public String getPesan() {
		return this.pesan;
	}

	public void setPesan(String pesan) {
		this.pesan = pesan;
	}

	@Column(name = "TITIK_ALERT", length = 50)
	public String getTitikAlert() {
		return this.titikAlert;
	}

	public void setTitikAlert(String titikAlert) {
		this.titikAlert = titikAlert;
	}

	@Column(name = "TUJUAN", length = 50)
	public String getTujuan() {
		return this.tujuan;
	}

	public void setTujuan(String tujuan) {
		this.tujuan = tujuan;
	}

	@Column(name = "OPERATOR_TUJUAN", length = 10)
	public String getOperatorTujuan() {
		return this.operatorTujuan;
	}

	public void setOperatorTujuan(String operatorTujuan) {
		this.operatorTujuan = operatorTujuan;
	}

	@Column(name = "MEDIA", length = 20)
	public String getMedia() {
		return this.media;
	}

	public void setMedia(String media) {
		this.media = media;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@DateTimeFormat(pattern = "dd/MM/yyyy hh:mm:ss a")
	@Column(name = "TANGGAL_KIRIM", length = 30)
	public String getTanggalKirim() {
		return this.tanggalKirim;
	}

	public void setTanggalKirim(String tanggalKirim) {
		this.tanggalKirim = tanggalKirim;
	}

	@DateTimeFormat(pattern = "dd/MM/yyyy hh:mm:ss a")
	@Column(name = "TANGGAL", length = 30)
	public String getTanggal() {
		return this.tanggal;
	}

	public void setTanggal(String tanggal) {
		this.tanggal = tanggal;
	}

}
