/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swamedia.soki.sms.view;

import java.awt.event.KeyEvent;
import java.math.BigDecimal;

import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import com.swamedia.soki.sms.config.DataHolder;
import com.swamedia.soki.sms.controller.OperatorController;
import com.swamedia.soki.sms.model.POperator;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author scatt labs
 */
public class ManagementNomorView extends javax.swing.JInternalFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form ManagementNomorView
	 */
	static ManagementNomorView managementNomorView;

	public static ManagementNomorView getInstance() {
		if (managementNomorView == null) {
			managementNomorView = new ManagementNomorView();
			managementNomorView.putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
			managementNomorView.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
			((BasicInternalFrameUI) managementNomorView.getUI()).setNorthPane(null);
			managementNomorView.setBorder(null);
		}
		return managementNomorView;
	}

	public ManagementNomorView() {
		initComponents();
		OperatorController.getInstance().populateTableOperator(this, "");
		OperatorController.getInstance().populateComboBoxOperator(this);
	}

	public javax.swing.JComboBox<String> getCbOperator() {
		return cbOperator;
	}

	public javax.swing.JTable getTableOperator() {
		return tableOperator;
	}

	public javax.swing.JTextField getTextNomor() {
		return textNomor;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void actionSearch() {
		buttonSearch.setEnabled(false);
		loading(true);
		OperatorController.getInstance().actionSearch(this);
		buttonSearch.setEnabled(true);
		loading(false);
		buttonSearch.requestFocus();
	}

	private void actionView() {
		try {
			int baris = tableOperator.getSelectedRow();
			if (baris < 0) {
				messageWarning();
			} else {
				loading(true);
				POperator operator = DataHolder.getInstance().getOperatorDao()
						.find(new BigDecimal(tableOperator.getValueAt(baris, 1).toString()));
				loading(false);
				EditNomorOperatorView enoView = new EditNomorOperatorView(MainForm.getInstance(), true, operator);
				enoView.setVisible(true);
			}
		} catch (Exception e) {
			loading(false);
			// TODO: handle exception
		}
	}

	private void messageWarning() {
		JOptionPane.showMessageDialog(this, "Pilih salah satu operator pada tabel", "Warning", 2);
	}

	public void actionReset() {
		OperatorController.getInstance().actionReset(this);
	}

	public void loading(boolean active) {
		if (active) {
			labelLoading.setIcon(
					new javax.swing.ImageIcon(getClass().getResource("/com/swamedia/soki/sms/images/loading3.gif")));
		} else {
			labelLoading.setIcon(null);
		}

	}

	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		cbOperator = new javax.swing.JComboBox<>();
		cbOperator.addKeyListener(new KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent evt) {
				if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
					textNomor.requestFocus();
				}
			}
		});
		jLabel2 = new javax.swing.JLabel();
		textNomor = new javax.swing.JTextField();
		buttonSearch = new javax.swing.JButton();
		buttonSearch.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				actionSearch();
			}
		});
		jPanel3 = new javax.swing.JPanel();
		buttonView = new javax.swing.JButton();
		buttonView.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				actionView();
			}
		});
		buttonEdit = new javax.swing.JButton();
		buttonEdit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				actionView();
			}
		});
		jScrollPane1 = new javax.swing.JScrollPane();
		tableOperator = new javax.swing.JTable();
		jLabel3 = new javax.swing.JLabel();

		setTitle("Content Management Nomor");
		setPreferredSize(new java.awt.Dimension(658, 441));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

		jLabel1.setText("Operator");

		cbOperator.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel2.setText("Nomor");

		textNomor.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				textNomorKeyTyped(evt);
			}

			@Override
			public void keyPressed(KeyEvent evt) {
				if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
					buttonSearch.requestFocus();
					actionSearch();
				}
			}
		});

		buttonSearch.setText("Search");

		JButton btnReset = new JButton("Reset");
		btnReset.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				actionReset();
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout
				.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel1)
										.addComponent(jLabel2))
								.addGap(18)
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(textNomor, GroupLayout.PREFERRED_SIZE, 129,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(cbOperator, GroupLayout.PREFERRED_SIZE, 261,
												GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(buttonSearch)
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(btnReset)))
				.addContainerGap(267, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel1).addComponent(
						cbOperator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(textNomor)
						.addComponent(jLabel2))
				.addGap(18).addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE).addComponent(buttonSearch)
						.addComponent(btnReset))
				.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2.setLayout(jPanel2Layout);

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

		buttonView.setText("View");
		buttonEdit.setText("Edit");
		tableOperator.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "", "Operator", "Nama", "Nomor" }));
		jScrollPane1.setViewportView(tableOperator);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel3Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jScrollPane1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createSequentialGroup().addComponent(buttonView)
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(buttonEdit)))
				.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE).addComponent(buttonEdit)
								.addComponent(buttonView))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE).addContainerGap()));
		jPanel3.setLayout(jPanel3Layout);

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel3.setText("Content Management Nomor");

		labelLoading = new JLabel("");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
												.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
												.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3)
														.addPreferredGap(ComponentPlacement.RELATED, 220,
																Short.MAX_VALUE)
														.addComponent(labelLoading)))
										.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel3)
								.addComponent(labelLoading, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE).addContainerGap()));
		jPanel1.setLayout(jPanel1Layout);

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void textNomorKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textNomorKeyTyped
		char c = evt.getKeyChar();
		if (textNomor.getText().length() >= 12) {
			getToolkit().beep();
			evt.consume();
		} else {
			if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
				getToolkit().beep();
				evt.consume();
			}
		}
	}// GEN-LAST:event_textNomorKeyTyped

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonSearch;
	private javax.swing.JButton buttonView;
	private javax.swing.JButton buttonEdit;
	private javax.swing.JComboBox<String> cbOperator;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JLabel labelLoading;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableOperator;
	private javax.swing.JTextField textNomor;
}
